#!/usr/bin/env php
<?php
// Clipea
// https://github.com/dave1010/clipea
// (c) 2023 Dave Hulbert

define('CLIPEA_DIR', __DIR__);

require_once CLIPEA_DIR . '/lib/cli.php';
require_once CLIPEA_DIR . '/lib/llm.php';

if (!shell_exec('which llm')) {
    die("Error: dependency 'llm' not found. Run 'clipea setup' to install\n");
}

$env = [
    'shell' => trim(shell_exec('ps -o comm= -p $(ps -o ppid= -p $(ps -o ppid= -p $$))')),
    'os' => PHP_OS,
    'editor' => getenv('EDITOR') ?? 'nano'
    // 'cwd' => getcwd(),
];

$system = file_get_contents(CLIPEA_DIR . '/system-prompt.txt') . json_encode($env);


function get_input(array $argv) {
    $argv = array_slice($argv, 1);
    $prompt = implode(' ', $argv);

    $stdin = get_stdin();
    if ($stdin) {
        if (strlen($stdin) > 8192) {
            die("Error: Input too long! Maximum 8192 characters allowed. Try limiting your input using 'head -c 8000 file.txt'.");
        }
        $prompt .= "\n~~~DATA~~~\n" . $stdin;
    }

    return $prompt;
}

$prompt = get_input($argv);

switch($prompt) {
    case 'alias':
        require_once CLIPEA_DIR . "/route/alias.php";
        // no exit
        break;
    case 'help':
    case '--help':
    case '-h':
        require_once CLIPEA_DIR . "/route/help.php";
        exit;
    case '':
        echo "Error: no query specified\n";
        exit;
    case 'env':
        require_once CLIPEA_DIR . "/route/env.php";
        exit;
    case 'setup':
        require_once CLIPEA_DIR . "/route/setup.php";
        exit;
}

// GPT-4 mode
$llmOpts = '';
if (substr($prompt, 0, 2) === '4 ') {
    $llmOpts = ' -m 4 ';
    $prompt = substr($prompt, 2);
}

echo "📎🟢 ";


// Look how simple this is!
// All it does is stream characters from the llm process and let you execute some of them
$line = '';
foreach (get_llm_response($system, $prompt, $llmOpts) as $char) {
    echo $char;
    $line .= $char;

    if ($char !== PHP_EOL) {
        continue;
    }

    if (substr($line, 0, 2) === '$ ') {
        maybe_passthru(substr($line, 2, -1)); // remove "$ " and \n
    }

    $line = '';
}
